### ISSUE TITLE
is it possible to put comment frame above the messages?

### ISSUE THREAD

**Issue by nirvana6** [aimingoo/gitmint#3]
Thanks for your work about `gitmint`. It's useful and powerful.

However, it's not convenient that the `commenting frame` lies at the bottom, or beneath a series of messages. Every time I want to leave a message I have to scroll a loooong webpage to reach the `commenting frame`. 

I think it will be easier for the user if the `commenting frame` can be put above the messages. In this situation, the user can directly comment **without scrooling too long webpage**.

Thanks for your consideration.

**Comment by nirvana6** [comment]
As you can see, I have to scrool a long distance to reach the `comment frame` annotated by red circle.
It's not so convenient.  It will be far better if the `comment frame` lies on the top.


![inkedlong webpage_li](https://user-images.githubusercontent.com/2957421/37092203-dc4d5318-2245-11e8-8b10-92796c227e08.jpg)

**Comment by aimingoo** [comment]
Ok... it's a good idea. i'll try this work as quickly as possible.

**Comment by aimingoo** [comment]
Done. a hotfix pushed.

try with 'above' option:

```javascript
var gitment = new Gitmint({
  above: true,
 ...
```
A example at here: [https://aimingoo.github.io/1-220.html](https://aimingoo.github.io/1-220.html)

**Comment by nirvana6** [comment]
@aimingoo wonderful work! I appreciate your job so much!! 

By the way, I use `NexT` theme of `hexo`. How can I configure it as you do ( in the `configure.yml` of [`hexo-theme-next`](https://github.com/theme-next/hexo-theme-next))?

**Comment by aimingoo** [comment]
Oh... the option can't integrate into `configuare.yml` in `NexT` theme, you must update file `gitment.swig` to use it.

Put the option at here:

https://github.com/theme-next/hexo-theme-next/blob/0e5ab0681b8677ec4b58734c3700440fb498b6eb/layout/_third-party/comments/gitment.swig#L27

**Comment by nirvana6** [comment]
@aimingoo I got it. And I will try it this night. Thanks in advance. 

By the way, shall I `git pull` within `hexo-theme-next` repo? Or else I shall directly revise the code of `swig`  in place as you?

**Comment by aimingoo** [comment]
@nirvana6 pull `hexo-theme-next` for your site, and insert option into `gitment.swig` in the theme of your site. these are your specific changes beyond original project.

**Comment by nirvana6** [comment]
@aimingoo precise explanation！
